
services:
  app:
    build: .
    container_name: productos-crud-app
    ports:
      - "3000:3000"
    volumes:
      - ./productos.db:/app/productos.db
      - ./node_modules:/app/node_modules
    restart: unless-stopped